-- =========================================================
-- A股情绪周期系统：最小页面渲染样本数据 MySQL
-- 说明：仅用于开发/联调页面渲染，不代表真实行情数据或任何交易建议。
-- 覆盖日期：2026-06-30 和 CURRENT_DATE()
-- 执行：docker exec -i astock-mysql mysql -uroot -pastock_root < sql/seed_minimal_mysql_render.sql
-- =========================================================
USE astock_business;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 清理本脚本历史样本，避免重复执行时主键冲突
DELETE FROM `rule_definition` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `rule_version` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `rule_version_audit_log` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `algorithm_task_log` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `data_quality_check_log` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `page_contract_field_lineage` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `cycle_sample_confirm` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `manual_stage_adjustment` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `pattern_risk_binding` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `buy_pattern_stage_matrix` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `buy_pattern_rule_config` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `risk_action_matrix` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `engine_batch_run_log` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `engine_batch_step_log` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `agent_audit_issue` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `agent_audit_result` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `agent_audit_rule_version` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `agent_audit_task` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `agent_release_gate_check` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `backtest_preset_template` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `backtest_report` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `backtest_rule_binding` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `backtest_task` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `backtest_task_param` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `backtest_task_progress` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `buy_pattern_definition` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `cycle_mining_task` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `daily_review_audit_log` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `daily_review_checklist` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `daily_review_record` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `daily_review_section` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `emotion_stage_rule_version` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `leader_manual_confirm` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `leader_rule_version` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `leader_type_definition` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `mainline_rule_version` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `risk_rule_version` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `rule_publish_check_log` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `sector_rule_version` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `similarity_rule_version` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `theme_definition` WHERE id BETWEEN 900000 AND 999999;
DELETE FROM `theme_stock_mapping` WHERE id BETWEEN 900000 AND 999999;

-- rule_definition
INSERT INTO `rule_definition` (`id`, `rule_code`, `rule_name`, `rule_category`, `rule_desc`, `rule_owner`, `rule_status`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900001, 'RULE_RENDER_000', '开发渲染规则', 'RENDER_SEED', '页面联调渲染规则样本', 'system', 'ENABLED', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_definition'), NOW(), NOW(), 0);

-- rule_version
INSERT INTO `rule_version` (`id`, `rule_code`, `rule_name`, `version_no`, `version_name`, `version_status`, `active_flag`, `rule_content_json`, `param_schema_json`, `publish_check_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900011, 'RULE_RENDER_001', '开发渲染规则', 'v1.0-render', '渲染样本版本', 'ACTIVE', 1, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_version'), NOW(), NOW(), 0);

-- rule_version_audit_log
INSERT INTO `rule_version_audit_log` (`id`, `rule_code`, `rule_version_id`, `operation_type`, `before_json`, `after_json`, `operator_name`, `audit_result`, `audit_message`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900021, 'RULE_RENDER_002', 900021, 'SEED', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_version_audit_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_version_audit_log'), 'system', 'PASSED', '样本审计通过', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_version_audit_log'), NOW(), NOW(), 0);

-- algorithm_task_log
INSERT INTO `algorithm_task_log` (`id`, `task_name`, `task_type`, `trade_date`, `task_status`, `started_at`, `finished_at`, `cost_millis`, `input_json`, `output_json`, `failure_reason`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900031, '页面渲染样本任务', 'RENDER_SEED', '2026-06-30', 'SUCCESS', NOW(), NOW(), 100, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'algorithm_task_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'algorithm_task_log'), '开发渲染样本：用于页面联调，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'algorithm_task_log'), NOW(), NOW(), 0);
INSERT INTO `algorithm_task_log` (`id`, `task_name`, `task_type`, `trade_date`, `task_status`, `started_at`, `finished_at`, `cost_millis`, `input_json`, `output_json`, `failure_reason`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900032, '页面渲染样本任务', 'RENDER_SEED', CURRENT_DATE(), 'SUCCESS', NOW(), NOW(), 100, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'algorithm_task_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'algorithm_task_log'), '开发渲染样本：用于页面联调，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'algorithm_task_log'), NOW(), NOW(), 0);

-- data_quality_check_log
INSERT INTO `data_quality_check_log` (`id`, `page_code`, `snapshot_code`, `snapshot_table`, `trade_date`, `market_scope`, `data_complete`, `completeness_ratio`, `critical`, `missing_reason`, `check_status`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900041, 'PAGE_RENDER_SEED', 'SNAPSHOT_RENDER_SEED', 'market_factor_snapshot', '2026-06-30', 'A_SHARE', 1, 1.000000, 1, '', 'PASSED', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'data_quality_check_log'), NOW(), NOW(), 0);
INSERT INTO `data_quality_check_log` (`id`, `page_code`, `snapshot_code`, `snapshot_table`, `trade_date`, `market_scope`, `data_complete`, `completeness_ratio`, `critical`, `missing_reason`, `check_status`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900042, 'PAGE_RENDER_SEED', 'SNAPSHOT_RENDER_SEED', 'market_factor_snapshot', CURRENT_DATE(), 'A_SHARE', 1, 1.000000, 1, '', 'PASSED', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'data_quality_check_log'), NOW(), NOW(), 0);

-- page_contract_field_lineage
INSERT INTO `page_contract_field_lineage` (`id`, `page_code`, `vo_class_name`, `field_name`, `source_type`, `source_table`, `source_column`, `calculation_formula`, `required`, `audit_passed`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900051, 'PAGE_RENDER_SEED', 'RenderSeedVO', 'seedField', 'CLICKHOUSE', 'market_factor_snapshot', 'trade_date', 'seed_field = source_field', 1, 1, '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'page_contract_field_lineage'), NOW(), NOW(), 0);

-- cycle_sample_confirm
INSERT INTO `cycle_sample_confirm` (`id`, `sample_id`, `cycle_sample_id`, `confirmed_stage`, `stage_code`, `confirm_status`, `confirm_user`, `confirm_reason`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900061, 900061, 900061, 'seed_cycle_sample_confirm_confirmed_stage', 'STAGE_REPAIR', 'CONFIRMED', 'system', '页面渲染样本确认', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_sample_confirm'), NOW(), NOW(), 0);

-- manual_stage_adjustment
INSERT INTO `manual_stage_adjustment` (`id`, `trade_date`, `market_scope`, `manual_stage`, `adjusted_stage`, `stage_code`, `adjust_reason`, `operator_name`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900071, '2026-06-30', 'A_SHARE', 'REPAIR', 'REPAIR', 'STAGE_REPAIR', '渲染样本阶段', 'system', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'manual_stage_adjustment'), NOW(), NOW(), 0);
INSERT INTO `manual_stage_adjustment` (`id`, `trade_date`, `market_scope`, `manual_stage`, `adjusted_stage`, `stage_code`, `adjust_reason`, `operator_name`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900072, CURRENT_DATE(), 'A_SHARE', 'REPAIR', 'REPAIR', 'STAGE_REPAIR', '渲染样本阶段', 'system', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'manual_stage_adjustment'), NOW(), NOW(), 0);

-- pattern_risk_binding
INSERT INTO `pattern_risk_binding` (`id`, `pattern_code`, `risk_code`, `risk_action`, `binding_status`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900081, 'PATTERN_RESEARCH_01', 'RISK_SENTIMENT', 'BLOCK_FULL_CONCLUSION', 'ENABLED', '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'pattern_risk_binding'), NOW(), NOW(), 0);

-- buy_pattern_stage_matrix
INSERT INTO `buy_pattern_stage_matrix` (`id`, `pattern_code`, `stage_code`, `matrix_score`, `matrix_status`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900091, 'PATTERN_RESEARCH_01', 'STAGE_REPAIR', 82.500000, 'ENABLED', '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_stage_matrix'), NOW(), NOW(), 0);

-- buy_pattern_rule_config
INSERT INTO `buy_pattern_rule_config` (`id`, `pattern_code`, `rule_code`, `rule_status`, `config_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900101, 'PATTERN_RESEARCH_01', 'RULE_RENDER_010', 'ENABLED', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_rule_config'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_rule_config'), NOW(), NOW(), 0);

-- risk_action_matrix
INSERT INTO `risk_action_matrix` (`id`, `risk_level`, `signal_level`, `risk_action`, `action_priority`, `description`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900111, 'seed_risk_action_matrix_risk_level', 'seed_risk_action_matrix_signal_level', 'BLOCK_FULL_CONCLUSION', 1, 'seed_risk_action_matrix_description', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_action_matrix'), NOW(), NOW(), 0);

-- engine_batch_run_log
INSERT INTO `engine_batch_run_log` (`id`, `trade_date`, `market_scope`, `batch_status`, `started_at`, `finished_at`, `cost_millis`, `total_step_count`, `success_step_count`, `failed_step_count`, `request_json`, `failure_reason`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900121, '2026-06-30', 'A_SHARE', 'SUCCESS', NOW(), NOW(), 100, 1, 1, 1, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'engine_batch_run_log'), '开发渲染样本：用于页面联调，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'engine_batch_run_log'), NOW(), NOW(), 0);
INSERT INTO `engine_batch_run_log` (`id`, `trade_date`, `market_scope`, `batch_status`, `started_at`, `finished_at`, `cost_millis`, `total_step_count`, `success_step_count`, `failed_step_count`, `request_json`, `failure_reason`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900122, CURRENT_DATE(), 'A_SHARE', 'SUCCESS', NOW(), NOW(), 100, 1, 1, 1, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'engine_batch_run_log'), '开发渲染样本：用于页面联调，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'engine_batch_run_log'), NOW(), NOW(), 0);

-- engine_batch_step_log
INSERT INTO `engine_batch_step_log` (`id`, `batch_id`, `step_no`, `step_code`, `step_name`, `engine_name`, `step_status`, `task_id`, `output_row_count`, `output_tables`, `failure_reason`, `summary_text`, `started_at`, `finished_at`, `cost_millis`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900131, 900131, 1, 'STEP_RENDER_SEED', '渲染样本步骤', 'RenderSeedEngine', 'SUCCESS', 900131, 1, 'seed_engine_batch_step_log_output_tables', '开发渲染样本：用于页面联调，不代表真实行情结论', '开发渲染样本：用于页面联调，不代表真实行情结论', NOW(), NOW(), 100, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'engine_batch_step_log'), NOW(), NOW(), 0);

-- agent_audit_issue
INSERT INTO `agent_audit_issue` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900141, '2026-06-30', 'A_SHARE', 'RULE_RENDER_014', '开发渲染规则', 900141, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900141, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), NOW(), NOW(), 0);
INSERT INTO `agent_audit_issue` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900142, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_014', '开发渲染规则', 900142, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900142, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_issue'), NOW(), NOW(), 0);

-- agent_audit_result
INSERT INTO `agent_audit_result` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900151, '2026-06-30', 'A_SHARE', 'RULE_RENDER_015', '开发渲染规则', 900151, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900151, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), NOW(), NOW(), 0);
INSERT INTO `agent_audit_result` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900152, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_015', '开发渲染规则', 900152, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900152, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_result'), NOW(), NOW(), 0);

-- agent_audit_rule_version
INSERT INTO `agent_audit_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900161, '2026-06-30', 'A_SHARE', 'RULE_RENDER_016', '开发渲染规则', 900161, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900161, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), NOW(), NOW(), 0);
INSERT INTO `agent_audit_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900162, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_016', '开发渲染规则', 900162, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900162, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_rule_version'), NOW(), NOW(), 0);

-- agent_audit_task
INSERT INTO `agent_audit_task` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900171, '2026-06-30', 'A_SHARE', 'RULE_RENDER_017', '开发渲染规则', 900171, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900171, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), NOW(), NOW(), 0);
INSERT INTO `agent_audit_task` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900172, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_017', '开发渲染规则', 900172, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900172, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_audit_task'), NOW(), NOW(), 0);

-- agent_release_gate_check
INSERT INTO `agent_release_gate_check` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900181, '2026-06-30', 'A_SHARE', 'RULE_RENDER_018', '开发渲染规则', 900181, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900181, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), NOW(), NOW(), 0);
INSERT INTO `agent_release_gate_check` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900182, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_018', '开发渲染规则', 900182, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900182, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'agent_release_gate_check'), NOW(), NOW(), 0);

-- backtest_preset_template
INSERT INTO `backtest_preset_template` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900191, '2026-06-30', 'A_SHARE', 'RULE_RENDER_019', '开发渲染规则', 900191, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900191, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), NOW(), NOW(), 0);
INSERT INTO `backtest_preset_template` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900192, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_019', '开发渲染规则', 900192, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900192, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_preset_template'), NOW(), NOW(), 0);

-- backtest_report
INSERT INTO `backtest_report` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900201, '2026-06-30', 'A_SHARE', 'RULE_RENDER_020', '开发渲染规则', 900201, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900201, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), NOW(), NOW(), 0);
INSERT INTO `backtest_report` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900202, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_020', '开发渲染规则', 900202, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900202, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_report'), NOW(), NOW(), 0);

-- backtest_rule_binding
INSERT INTO `backtest_rule_binding` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900211, '2026-06-30', 'A_SHARE', 'RULE_RENDER_021', '开发渲染规则', 900211, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900211, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), NOW(), NOW(), 0);
INSERT INTO `backtest_rule_binding` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900212, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_021', '开发渲染规则', 900212, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900212, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_rule_binding'), NOW(), NOW(), 0);

-- backtest_task
INSERT INTO `backtest_task` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900221, '2026-06-30', 'A_SHARE', 'RULE_RENDER_022', '开发渲染规则', 900221, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900221, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), NOW(), NOW(), 0);
INSERT INTO `backtest_task` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900222, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_022', '开发渲染规则', 900222, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900222, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task'), NOW(), NOW(), 0);

-- backtest_task_param
INSERT INTO `backtest_task_param` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900231, '2026-06-30', 'A_SHARE', 'RULE_RENDER_023', '开发渲染规则', 900231, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900231, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), NOW(), NOW(), 0);
INSERT INTO `backtest_task_param` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900232, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_023', '开发渲染规则', 900232, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900232, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_param'), NOW(), NOW(), 0);

-- backtest_task_progress
INSERT INTO `backtest_task_progress` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900241, '2026-06-30', 'A_SHARE', 'RULE_RENDER_024', '开发渲染规则', 900241, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900241, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), NOW(), NOW(), 0);
INSERT INTO `backtest_task_progress` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900242, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_024', '开发渲染规则', 900242, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900242, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'backtest_task_progress'), NOW(), NOW(), 0);

-- buy_pattern_definition
INSERT INTO `buy_pattern_definition` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900251, '2026-06-30', 'A_SHARE', 'RULE_RENDER_025', '开发渲染规则', 900251, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900251, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), NOW(), NOW(), 0);
INSERT INTO `buy_pattern_definition` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900252, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_025', '开发渲染规则', 900252, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900252, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'buy_pattern_definition'), NOW(), NOW(), 0);

-- cycle_mining_task
INSERT INTO `cycle_mining_task` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900261, '2026-06-30', 'A_SHARE', 'RULE_RENDER_026', '开发渲染规则', 900261, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900261, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), NOW(), NOW(), 0);
INSERT INTO `cycle_mining_task` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900262, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_026', '开发渲染规则', 900262, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900262, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'cycle_mining_task'), NOW(), NOW(), 0);

-- daily_review_audit_log
INSERT INTO `daily_review_audit_log` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900271, '2026-06-30', 'A_SHARE', 'RULE_RENDER_027', '开发渲染规则', 900271, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900271, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), NOW(), NOW(), 0);
INSERT INTO `daily_review_audit_log` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900272, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_027', '开发渲染规则', 900272, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900272, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_audit_log'), NOW(), NOW(), 0);

-- daily_review_checklist
INSERT INTO `daily_review_checklist` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900281, '2026-06-30', 'A_SHARE', 'RULE_RENDER_028', '开发渲染规则', 900281, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900281, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), NOW(), NOW(), 0);
INSERT INTO `daily_review_checklist` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900282, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_028', '开发渲染规则', 900282, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900282, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_checklist'), NOW(), NOW(), 0);

-- daily_review_record
INSERT INTO `daily_review_record` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900291, '2026-06-30', 'A_SHARE', 'RULE_RENDER_029', '开发渲染规则', 900291, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900291, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), NOW(), NOW(), 0);
INSERT INTO `daily_review_record` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900292, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_029', '开发渲染规则', 900292, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900292, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_record'), NOW(), NOW(), 0);

-- daily_review_section
INSERT INTO `daily_review_section` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900301, '2026-06-30', 'A_SHARE', 'RULE_RENDER_030', '开发渲染规则', 900301, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900301, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), NOW(), NOW(), 0);
INSERT INTO `daily_review_section` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900302, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_030', '开发渲染规则', 900302, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900302, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'daily_review_section'), NOW(), NOW(), 0);

-- emotion_stage_rule_version
INSERT INTO `emotion_stage_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900311, '2026-06-30', 'A_SHARE', 'RULE_RENDER_031', '开发渲染规则', 900311, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900311, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), NOW(), NOW(), 0);
INSERT INTO `emotion_stage_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900312, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_031', '开发渲染规则', 900312, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900312, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'emotion_stage_rule_version'), NOW(), NOW(), 0);

-- leader_manual_confirm
INSERT INTO `leader_manual_confirm` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900321, '2026-06-30', 'A_SHARE', 'RULE_RENDER_032', '开发渲染规则', 900321, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900321, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), NOW(), NOW(), 0);
INSERT INTO `leader_manual_confirm` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900322, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_032', '开发渲染规则', 900322, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900322, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_manual_confirm'), NOW(), NOW(), 0);

-- leader_rule_version
INSERT INTO `leader_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900331, '2026-06-30', 'A_SHARE', 'RULE_RENDER_033', '开发渲染规则', 900331, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900331, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), NOW(), NOW(), 0);
INSERT INTO `leader_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900332, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_033', '开发渲染规则', 900332, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900332, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_rule_version'), NOW(), NOW(), 0);

-- leader_type_definition
INSERT INTO `leader_type_definition` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900341, '2026-06-30', 'A_SHARE', 'RULE_RENDER_034', '开发渲染规则', 900341, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900341, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), NOW(), NOW(), 0);
INSERT INTO `leader_type_definition` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900342, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_034', '开发渲染规则', 900342, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900342, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'leader_type_definition'), NOW(), NOW(), 0);

-- mainline_rule_version
INSERT INTO `mainline_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900351, '2026-06-30', 'A_SHARE', 'RULE_RENDER_035', '开发渲染规则', 900351, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900351, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), NOW(), NOW(), 0);
INSERT INTO `mainline_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900352, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_035', '开发渲染规则', 900352, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900352, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'mainline_rule_version'), NOW(), NOW(), 0);

-- risk_rule_version
INSERT INTO `risk_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900361, '2026-06-30', 'A_SHARE', 'RULE_RENDER_036', '开发渲染规则', 900361, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900361, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), NOW(), NOW(), 0);
INSERT INTO `risk_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900362, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_036', '开发渲染规则', 900362, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900362, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'risk_rule_version'), NOW(), NOW(), 0);

-- rule_publish_check_log
INSERT INTO `rule_publish_check_log` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900371, '2026-06-30', 'A_SHARE', 'RULE_RENDER_037', '开发渲染规则', 900371, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900371, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), NOW(), NOW(), 0);
INSERT INTO `rule_publish_check_log` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900372, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_037', '开发渲染规则', 900372, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900372, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'rule_publish_check_log'), NOW(), NOW(), 0);

-- sector_rule_version
INSERT INTO `sector_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900381, '2026-06-30', 'A_SHARE', 'RULE_RENDER_038', '开发渲染规则', 900381, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900381, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), NOW(), NOW(), 0);
INSERT INTO `sector_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900382, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_038', '开发渲染规则', 900382, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900382, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'sector_rule_version'), NOW(), NOW(), 0);

-- similarity_rule_version
INSERT INTO `similarity_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900391, '2026-06-30', 'A_SHARE', 'RULE_RENDER_039', '开发渲染规则', 900391, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900391, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), NOW(), NOW(), 0);
INSERT INTO `similarity_rule_version` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900392, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_039', '开发渲染规则', 900392, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900392, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'similarity_rule_version'), NOW(), NOW(), 0);

-- theme_definition
INSERT INTO `theme_definition` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900401, '2026-06-30', 'A_SHARE', 'RULE_RENDER_040', '开发渲染规则', 900401, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900401, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), NOW(), NOW(), 0);
INSERT INTO `theme_definition` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900402, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_040', '开发渲染规则', 900402, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900402, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_definition'), NOW(), NOW(), 0);

-- theme_stock_mapping
INSERT INTO `theme_stock_mapping` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900411, '2026-06-30', 'A_SHARE', 'RULE_RENDER_041', '开发渲染规则', 900411, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900411, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), NOW(), NOW(), 0);
INSERT INTO `theme_stock_mapping` (`id`, `trade_date`, `market_scope`, `rule_code`, `rule_name`, `rule_version_id`, `version_no`, `version_status`, `business_code`, `business_name`, `task_id`, `task_status`, `page_code`, `stock_code`, `stock_name`, `theme_code`, `theme_name`, `mainline_code`, `mainline_name`, `pattern_code`, `pattern_name`, `risk_code`, `risk_name`, `status`, `score`, `config_json`, `param_json`, `result_json`, `evidence_json`, `remark`, `features`, `created_at`, `updated_at`, `is_deleted`) VALUES (900412, CURRENT_DATE(), 'A_SHARE', 'RULE_RENDER_041', '开发渲染规则', 900412, 'v1.0-render', 'ACTIVE', 'BIZ_RENDER_SEED', '页面渲染样本', 900412, 'SUCCESS', 'PAGE_RENDER_SEED', '000001', '平安银行', 'THEME_AI_APP', 'AI应用', 'ML_AI_APP', 'AI应用主线', 'PATTERN_RESEARCH_01', '条件观察模式', 'RISK_SENTIMENT', '情绪波动风险', 'ACTIVE', 82.500000, JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), '开发渲染样本，不代表真实行情结论', JSON_OBJECT('seed', true, 'purpose', 'page_render', 'table_name', 'theme_stock_mapping'), NOW(), NOW(), 0);

SET FOREIGN_KEY_CHECKS = 1;

-- 验证示例：
-- SELECT COUNT(*) FROM rule_version WHERE id BETWEEN 900000 AND 999999;
-- SELECT COUNT(*) FROM data_quality_check_log WHERE id BETWEEN 900000 AND 999999;
