-- =========================================================
-- A股情绪周期复盘与历史相似行情回测系统
-- MySQL 完整初始化脚本 V2
-- 文件名：init_mysql.sql
-- 生成日期：2026-06-30
-- 适用版本：MySQL 8.0+
--
-- 这版已经按最终交付包 Java 代码中的 *Sql.java / *Mapper.java 重新扫描对齐。
-- 覆盖 42 张 MySQL 表：
--   业务配置、规则版本、数据质量、复盘、回测、Agent审计、一键跑批等。
--
-- 执行方式：
--   mysql -uroot -p < init_mysql.sql
-- =========================================================

create database if not exists astock_business
  default character set utf8mb4
  collate utf8mb4_unicode_ci;

use astock_business;

-- =========================================================
-- 01. 核心 MySQL DDL
-- 来源：sql/20_mysql_full_schema.sql
-- =========================================================

-- 第八步：MySQL业务库完整DDL
-- 目标：与当前 Java Engine / Repository / Mapper / AgentAudit / 字段血缘闭环对齐
-- 数据库：MySQL 8.0+
-- 执行建议：
--   create database astock_business default character set utf8mb4 collate utf8mb4_unicode_ci;
--   use astock_business;
--   source sql/20_mysql_full_schema.sql;

set names utf8mb4;
set foreign_key_checks = 0;

create table if not exists rule_definition (
    id bigint primary key auto_increment comment '主键ID',
    rule_code varchar(128) not null comment '规则编码',
    rule_name varchar(255) not null comment '规则名称',
    rule_category varchar(64) not null comment '规则分类',
    rule_desc varchar(1000) null comment '规则说明',
    rule_owner varchar(128) null comment '规则负责人',
    rule_status varchar(32) not null default 'ENABLED' comment '规则状态',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    unique key uk_rule_definition_code (rule_code),
    key idx_rule_definition_category (rule_category, rule_status, is_deleted)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='规则定义表';

create table if not exists rule_version (
    id bigint primary key auto_increment comment '规则版本ID',
    rule_code varchar(128) not null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    version_no varchar(64) not null comment '版本号',
    version_name varchar(255) null comment '版本名称',
    version_status varchar(32) not null default 'DRAFT' comment '版本状态：DRAFT/ACTIVE/ARCHIVED',
    active_flag tinyint not null default 0 comment '是否启用版本',
    rule_content_json json null comment '规则内容JSON',
    param_schema_json json null comment '参数结构JSON',
    publish_check_json json null comment '发布检查JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    unique key uk_rule_version (rule_code, version_no),
    key idx_rule_version_rule_status (rule_code, version_status, is_deleted),
    key idx_rule_version_active (rule_code, active_flag, is_deleted)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='规则版本表';

create table if not exists rule_version_audit_log (
    id bigint primary key auto_increment comment '主键ID',
    rule_code varchar(128) not null comment '规则编码',
    rule_version_id bigint not null comment '规则版本ID',
    operation_type varchar(64) not null comment '操作类型',
    before_json json null comment '变更前JSON',
    after_json json null comment '变更后JSON',
    operator_name varchar(128) null comment '操作人',
    audit_result varchar(32) null comment '审计结果',
    audit_message varchar(1000) null comment '审计信息',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_rule_version_audit_rule (rule_code, rule_version_id, created_at),
    key idx_rule_version_audit_operation (operation_type, created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='规则版本审计日志表';

create table if not exists algorithm_task_log (
    id bigint primary key auto_increment comment '算法任务ID',
    task_name varchar(255) not null comment '任务名称',
    task_type varchar(128) not null comment '任务类型',
    trade_date date null comment '交易日',
    task_status varchar(64) not null comment '任务状态',
    started_at datetime null comment '开始时间',
    finished_at datetime null comment '结束时间',
    cost_millis bigint null comment '耗时毫秒',
    input_json json null comment '输入参数JSON',
    output_json json null comment '输出JSON',
    failure_reason text null comment '失败原因',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_algorithm_task_log_type_date (task_type, trade_date, task_status),
    key idx_algorithm_task_log_created (created_at),
    key idx_algorithm_task_log_status (task_status, started_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='算法任务执行日志表';

create table if not exists data_quality_check_log (
    id bigint primary key auto_increment comment '主键ID',
    page_code varchar(128) null comment '页面编码或任务编码',
    snapshot_code varchar(128) null comment '快照编码',
    snapshot_table varchar(128) not null comment '快照表名',
    trade_date date not null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    data_complete tinyint not null default 0 comment '数据是否完整',
    completeness_ratio decimal(18,6) null comment '完整率',
    critical tinyint not null default 0 comment '是否关键数据',
    missing_reason varchar(1000) null comment '缺失原因',
    check_status varchar(64) not null default 'CHECKED' comment '检查状态',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_data_quality_check_log_page_date (page_code, trade_date, is_deleted),
    key idx_data_quality_check_log_snapshot (snapshot_table, trade_date, is_deleted),
    key idx_data_quality_check_log_scope (market_scope, trade_date, data_complete)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='数据完整性检查日志表';

create table if not exists page_contract_field_lineage (
    id bigint primary key auto_increment comment '主键ID',
    page_code varchar(128) not null comment '页面编码',
    vo_class_name varchar(255) not null comment 'VO类名',
    field_name varchar(255) not null comment '字段名',
    source_type varchar(64) not null comment '来源类型：MYSQL/CLICKHOUSE/FORMULA/CONSTANT',
    source_table varchar(128) null comment '来源表',
    source_column varchar(128) null comment '来源列',
    calculation_formula varchar(2000) null comment '计算公式',
    required tinyint not null default 0 comment '是否必填',
    audit_passed tinyint not null default 1 comment '审计是否通过',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    unique key uk_page_field_lineage (page_code, vo_class_name, field_name, source_table, source_column),
    key idx_page_contract_field_lineage_page (page_code, vo_class_name, is_deleted),
    key idx_page_contract_field_lineage_source (source_type, source_table, source_column, is_deleted)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='页面字段血缘契约表';

create table if not exists cycle_sample_confirm (
    id bigint primary key auto_increment comment '主键ID',
    sample_id bigint not null comment '历史样本ID',
    cycle_sample_id bigint null comment '周期样本ID',
    confirmed_stage varchar(64) null comment '人工确认阶段',
    stage_code varchar(64) null comment '阶段编码',
    confirm_status varchar(64) not null default 'CONFIRMED' comment '确认状态',
    confirm_user varchar(128) null comment '确认人',
    confirm_reason varchar(1000) null comment '确认原因',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_cycle_sample_confirm_sample (sample_id, confirm_status, is_deleted),
    key idx_cycle_sample_confirm_stage (confirmed_stage, is_deleted),
    key idx_cycle_sample_confirm_cycle (cycle_sample_id, is_deleted)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='历史周期样本人工确认表';

create table if not exists manual_stage_adjustment (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date not null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    manual_stage varchar(64) null comment '人工阶段',
    adjusted_stage varchar(64) null comment '修正后阶段',
    stage_code varchar(64) null comment '阶段编码',
    adjust_reason varchar(1000) null comment '修正原因',
    operator_name varchar(128) null comment '操作人',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_manual_stage_adjustment_date (trade_date, adjusted_stage, is_deleted),
    key idx_manual_stage_adjustment_scope (market_scope, trade_date, is_deleted)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='情绪阶段人工修正表';

create table if not exists pattern_risk_binding (
    id bigint primary key auto_increment comment '主键ID',
    pattern_code varchar(128) not null comment '模式编码',
    risk_code varchar(128) null comment '风险编码',
    risk_action varchar(64) not null comment '风险动作',
    binding_status varchar(64) not null default 'ENABLED' comment '绑定状态',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_pattern_risk_binding_pattern (pattern_code, risk_action, is_deleted),
    key idx_pattern_risk_binding_risk (risk_code, binding_status, is_deleted)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='模式与风险动作绑定表';

create table if not exists buy_pattern_stage_matrix (
    id bigint primary key auto_increment comment '主键ID',
    pattern_code varchar(128) not null comment '模式编码',
    stage_code varchar(64) not null comment '情绪阶段编码',
    matrix_score decimal(18,6) null comment '矩阵分',
    matrix_status varchar(64) not null default 'ENABLED' comment '矩阵状态',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_buy_pattern_stage_matrix_pattern_stage (pattern_code, stage_code, is_deleted)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='买点模式与情绪阶段矩阵表';

create table if not exists buy_pattern_rule_config (
    id bigint primary key auto_increment comment '主键ID',
    pattern_code varchar(128) not null comment '模式编码',
    rule_code varchar(128) null comment '规则编码',
    rule_status varchar(64) not null default 'ENABLED' comment '规则状态',
    config_json json null comment '配置JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_buy_pattern_rule_config_pattern (pattern_code, rule_status, is_deleted)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='买点模式规则配置表';

create table if not exists risk_action_matrix (
    id bigint primary key auto_increment comment '主键ID',
    risk_level varchar(64) not null comment '风险等级',
    signal_level varchar(64) null comment '信号等级',
    risk_action varchar(64) not null comment '风险动作',
    action_priority int not null default 0 comment '动作优先级',
    description varchar(1000) null comment '说明',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_risk_action_matrix_level (risk_level, risk_action, is_deleted),
    key idx_risk_action_matrix_priority (action_priority)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='风控动作矩阵表';

set foreign_key_checks = 1;

-- =========================================================
-- 02. Engine 一键跑批日志表
-- 来源：sql/23_mysql_engine_batch_schema.sql
-- =========================================================

-- 第十步：Engine一键跑批批次日志表
-- 数据库：MySQL 8.0+
-- 执行前：use astock_business;

create table if not exists engine_batch_run_log (
    id bigint primary key auto_increment comment '批次ID',
    trade_date date not null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    batch_status varchar(64) not null comment '批次状态：RUNNING/SUCCESS/FAILED',
    started_at datetime not null comment '开始时间',
    finished_at datetime null comment '结束时间',
    cost_millis bigint null comment '耗时毫秒',
    total_step_count int null comment '总步骤数',
    success_step_count int null comment '成功步骤数',
    failed_step_count int null comment '失败步骤数',
    request_json json null comment '请求JSON',
    failure_reason text null comment '失败原因',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_engine_batch_run_date (trade_date, market_scope, batch_status),
    key idx_engine_batch_run_started (started_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Engine一键跑批批次日志表';

create table if not exists engine_batch_step_log (
    id bigint primary key auto_increment comment '步骤日志ID',
    batch_id bigint not null comment '批次ID',
    step_no int not null comment '步骤序号',
    step_code varchar(128) not null comment '步骤编码',
    step_name varchar(255) not null comment '步骤名称',
    engine_name varchar(255) not null comment '引擎名称',
    step_status varchar(64) not null comment '步骤状态：SUCCESS/FAILED',
    task_id bigint null comment '底层算法任务ID',
    output_row_count int null comment '输出行数',
    output_tables varchar(1000) null comment '输出表列表',
    failure_reason text null comment '失败原因',
    summary_text text null comment '摘要',
    started_at datetime not null comment '开始时间',
    finished_at datetime null comment '结束时间',
    cost_millis bigint null comment '耗时毫秒',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_engine_batch_step_batch (batch_id, step_no),
    key idx_engine_batch_step_status (step_status, engine_name),
    key idx_engine_batch_step_task (task_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Engine一键跑批步骤日志表';

-- =========================================================
-- 03. 最终代码扫描后补齐的 MySQL 支撑表
-- 补齐表数量：28
-- =========================================================

create table if not exists agent_audit_issue (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_agent_audit_issue_date (trade_date, market_scope, is_deleted),
    key idx_agent_audit_issue_business (business_code, status, is_deleted),
    key idx_agent_audit_issue_rule (rule_code, rule_version_id, is_deleted),
    key idx_agent_audit_issue_task (task_id, task_status, is_deleted),
    key idx_agent_audit_issue_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Agent审计问题业务表';

create table if not exists agent_audit_result (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_agent_audit_result_date (trade_date, market_scope, is_deleted),
    key idx_agent_audit_result_business (business_code, status, is_deleted),
    key idx_agent_audit_result_rule (rule_code, rule_version_id, is_deleted),
    key idx_agent_audit_result_task (task_id, task_status, is_deleted),
    key idx_agent_audit_result_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Agent审计结果业务表';

create table if not exists agent_audit_rule_version (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_agent_audit_rule_version_date (trade_date, market_scope, is_deleted),
    key idx_agent_audit_rule_version_business (business_code, status, is_deleted),
    key idx_agent_audit_rule_version_rule (rule_code, rule_version_id, is_deleted),
    key idx_agent_audit_rule_version_task (task_id, task_status, is_deleted),
    key idx_agent_audit_rule_version_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Agent审计规则版本业务表';

create table if not exists agent_audit_task (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_agent_audit_task_date (trade_date, market_scope, is_deleted),
    key idx_agent_audit_task_business (business_code, status, is_deleted),
    key idx_agent_audit_task_rule (rule_code, rule_version_id, is_deleted),
    key idx_agent_audit_task_task (task_id, task_status, is_deleted),
    key idx_agent_audit_task_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Agent审计任务表';

create table if not exists agent_release_gate_check (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_agent_release_gate_check_date (trade_date, market_scope, is_deleted),
    key idx_agent_release_gate_check_business (business_code, status, is_deleted),
    key idx_agent_release_gate_check_rule (rule_code, rule_version_id, is_deleted),
    key idx_agent_release_gate_check_task (task_id, task_status, is_deleted),
    key idx_agent_release_gate_check_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Agent发布闸门检查业务表';

create table if not exists backtest_preset_template (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_backtest_preset_template_date (trade_date, market_scope, is_deleted),
    key idx_backtest_preset_template_business (business_code, status, is_deleted),
    key idx_backtest_preset_template_rule (rule_code, rule_version_id, is_deleted),
    key idx_backtest_preset_template_task (task_id, task_status, is_deleted),
    key idx_backtest_preset_template_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='回测预设模板表';

create table if not exists backtest_report (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_backtest_report_date (trade_date, market_scope, is_deleted),
    key idx_backtest_report_business (business_code, status, is_deleted),
    key idx_backtest_report_rule (rule_code, rule_version_id, is_deleted),
    key idx_backtest_report_task (task_id, task_status, is_deleted),
    key idx_backtest_report_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='回测报告业务表';

create table if not exists backtest_rule_binding (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_backtest_rule_binding_date (trade_date, market_scope, is_deleted),
    key idx_backtest_rule_binding_business (business_code, status, is_deleted),
    key idx_backtest_rule_binding_rule (rule_code, rule_version_id, is_deleted),
    key idx_backtest_rule_binding_task (task_id, task_status, is_deleted),
    key idx_backtest_rule_binding_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='回测规则绑定表';

create table if not exists backtest_task (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_backtest_task_date (trade_date, market_scope, is_deleted),
    key idx_backtest_task_business (business_code, status, is_deleted),
    key idx_backtest_task_rule (rule_code, rule_version_id, is_deleted),
    key idx_backtest_task_task (task_id, task_status, is_deleted),
    key idx_backtest_task_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='回测任务表';

create table if not exists backtest_task_param (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_backtest_task_param_date (trade_date, market_scope, is_deleted),
    key idx_backtest_task_param_business (business_code, status, is_deleted),
    key idx_backtest_task_param_rule (rule_code, rule_version_id, is_deleted),
    key idx_backtest_task_param_task (task_id, task_status, is_deleted),
    key idx_backtest_task_param_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='回测任务参数表';

create table if not exists backtest_task_progress (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_backtest_task_progress_date (trade_date, market_scope, is_deleted),
    key idx_backtest_task_progress_business (business_code, status, is_deleted),
    key idx_backtest_task_progress_rule (rule_code, rule_version_id, is_deleted),
    key idx_backtest_task_progress_task (task_id, task_status, is_deleted),
    key idx_backtest_task_progress_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='回测任务进度表';

create table if not exists buy_pattern_definition (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_buy_pattern_definition_date (trade_date, market_scope, is_deleted),
    key idx_buy_pattern_definition_business (business_code, status, is_deleted),
    key idx_buy_pattern_definition_rule (rule_code, rule_version_id, is_deleted),
    key idx_buy_pattern_definition_task (task_id, task_status, is_deleted),
    key idx_buy_pattern_definition_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='买点模式定义表';

create table if not exists cycle_mining_task (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_cycle_mining_task_date (trade_date, market_scope, is_deleted),
    key idx_cycle_mining_task_business (business_code, status, is_deleted),
    key idx_cycle_mining_task_rule (rule_code, rule_version_id, is_deleted),
    key idx_cycle_mining_task_task (task_id, task_status, is_deleted),
    key idx_cycle_mining_task_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='周期样本挖掘任务表';

create table if not exists daily_review_audit_log (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_daily_review_audit_log_date (trade_date, market_scope, is_deleted),
    key idx_daily_review_audit_log_business (business_code, status, is_deleted),
    key idx_daily_review_audit_log_rule (rule_code, rule_version_id, is_deleted),
    key idx_daily_review_audit_log_task (task_id, task_status, is_deleted),
    key idx_daily_review_audit_log_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='每日复盘审计日志表';

create table if not exists daily_review_checklist (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_daily_review_checklist_date (trade_date, market_scope, is_deleted),
    key idx_daily_review_checklist_business (business_code, status, is_deleted),
    key idx_daily_review_checklist_rule (rule_code, rule_version_id, is_deleted),
    key idx_daily_review_checklist_task (task_id, task_status, is_deleted),
    key idx_daily_review_checklist_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='每日复盘检查清单表';

create table if not exists daily_review_record (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_daily_review_record_date (trade_date, market_scope, is_deleted),
    key idx_daily_review_record_business (business_code, status, is_deleted),
    key idx_daily_review_record_rule (rule_code, rule_version_id, is_deleted),
    key idx_daily_review_record_task (task_id, task_status, is_deleted),
    key idx_daily_review_record_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='每日复盘记录表';

create table if not exists daily_review_section (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_daily_review_section_date (trade_date, market_scope, is_deleted),
    key idx_daily_review_section_business (business_code, status, is_deleted),
    key idx_daily_review_section_rule (rule_code, rule_version_id, is_deleted),
    key idx_daily_review_section_task (task_id, task_status, is_deleted),
    key idx_daily_review_section_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='每日复盘章节表';

create table if not exists emotion_stage_rule_version (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_emotion_stage_rule_version_date (trade_date, market_scope, is_deleted),
    key idx_emotion_stage_rule_version_business (business_code, status, is_deleted),
    key idx_emotion_stage_rule_version_rule (rule_code, rule_version_id, is_deleted),
    key idx_emotion_stage_rule_version_task (task_id, task_status, is_deleted),
    key idx_emotion_stage_rule_version_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='情绪阶段规则版本展示表';

create table if not exists leader_manual_confirm (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_leader_manual_confirm_date (trade_date, market_scope, is_deleted),
    key idx_leader_manual_confirm_business (business_code, status, is_deleted),
    key idx_leader_manual_confirm_rule (rule_code, rule_version_id, is_deleted),
    key idx_leader_manual_confirm_task (task_id, task_status, is_deleted),
    key idx_leader_manual_confirm_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='龙头人工确认表';

create table if not exists leader_rule_version (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_leader_rule_version_date (trade_date, market_scope, is_deleted),
    key idx_leader_rule_version_business (business_code, status, is_deleted),
    key idx_leader_rule_version_rule (rule_code, rule_version_id, is_deleted),
    key idx_leader_rule_version_task (task_id, task_status, is_deleted),
    key idx_leader_rule_version_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='龙头规则版本展示表';

create table if not exists leader_type_definition (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_leader_type_definition_date (trade_date, market_scope, is_deleted),
    key idx_leader_type_definition_business (business_code, status, is_deleted),
    key idx_leader_type_definition_rule (rule_code, rule_version_id, is_deleted),
    key idx_leader_type_definition_task (task_id, task_status, is_deleted),
    key idx_leader_type_definition_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='龙头类型定义表';

create table if not exists mainline_rule_version (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_mainline_rule_version_date (trade_date, market_scope, is_deleted),
    key idx_mainline_rule_version_business (business_code, status, is_deleted),
    key idx_mainline_rule_version_rule (rule_code, rule_version_id, is_deleted),
    key idx_mainline_rule_version_task (task_id, task_status, is_deleted),
    key idx_mainline_rule_version_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='主线规则版本展示表';

create table if not exists risk_rule_version (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_risk_rule_version_date (trade_date, market_scope, is_deleted),
    key idx_risk_rule_version_business (business_code, status, is_deleted),
    key idx_risk_rule_version_rule (rule_code, rule_version_id, is_deleted),
    key idx_risk_rule_version_task (task_id, task_status, is_deleted),
    key idx_risk_rule_version_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='风控规则版本展示表';

create table if not exists rule_publish_check_log (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_rule_publish_check_log_date (trade_date, market_scope, is_deleted),
    key idx_rule_publish_check_log_business (business_code, status, is_deleted),
    key idx_rule_publish_check_log_rule (rule_code, rule_version_id, is_deleted),
    key idx_rule_publish_check_log_task (task_id, task_status, is_deleted),
    key idx_rule_publish_check_log_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='规则发布检查日志表';

create table if not exists sector_rule_version (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_sector_rule_version_date (trade_date, market_scope, is_deleted),
    key idx_sector_rule_version_business (business_code, status, is_deleted),
    key idx_sector_rule_version_rule (rule_code, rule_version_id, is_deleted),
    key idx_sector_rule_version_task (task_id, task_status, is_deleted),
    key idx_sector_rule_version_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='板块规则版本展示表';

create table if not exists similarity_rule_version (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_similarity_rule_version_date (trade_date, market_scope, is_deleted),
    key idx_similarity_rule_version_business (business_code, status, is_deleted),
    key idx_similarity_rule_version_rule (rule_code, rule_version_id, is_deleted),
    key idx_similarity_rule_version_task (task_id, task_status, is_deleted),
    key idx_similarity_rule_version_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='相似度规则版本展示表';

create table if not exists theme_definition (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_theme_definition_date (trade_date, market_scope, is_deleted),
    key idx_theme_definition_business (business_code, status, is_deleted),
    key idx_theme_definition_rule (rule_code, rule_version_id, is_deleted),
    key idx_theme_definition_task (task_id, task_status, is_deleted),
    key idx_theme_definition_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='题材定义表';

create table if not exists theme_stock_mapping (
    id bigint primary key auto_increment comment '主键ID',
    trade_date date null comment '交易日',
    market_scope varchar(64) not null default 'A_SHARE' comment '市场范围',
    rule_code varchar(128) null comment '规则编码',
    rule_name varchar(255) null comment '规则名称',
    rule_version_id bigint null comment '规则版本ID',
    version_no varchar(64) null comment '版本号',
    version_status varchar(64) null comment '版本状态',
    business_code varchar(128) null comment '业务编码',
    business_name varchar(255) null comment '业务名称',
    task_id bigint null comment '任务ID',
    task_status varchar(64) null comment '任务状态',
    page_code varchar(128) null comment '页面编码',
    stock_code varchar(32) null comment '股票代码',
    stock_name varchar(128) null comment '股票名称',
    theme_code varchar(128) null comment '题材编码',
    theme_name varchar(255) null comment '题材名称',
    mainline_code varchar(128) null comment '主线编码',
    mainline_name varchar(255) null comment '主线名称',
    pattern_code varchar(128) null comment '模式编码',
    pattern_name varchar(255) null comment '模式名称',
    risk_code varchar(128) null comment '风险编码',
    risk_name varchar(255) null comment '风险名称',
    status varchar(64) null comment '状态',
    score decimal(18,6) null comment '评分',
    config_json json null comment '配置JSON',
    param_json json null comment '参数JSON',
    result_json json null comment '结果JSON',
    evidence_json json null comment '证据JSON',
    remark varchar(1000) null comment '备注',
    features json null comment '扩展字段',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    is_deleted tinyint not null default 0 comment '逻辑删除：0否1是',
    key idx_theme_stock_mapping_date (trade_date, market_scope, is_deleted),
    key idx_theme_stock_mapping_business (business_code, status, is_deleted),
    key idx_theme_stock_mapping_rule (rule_code, rule_version_id, is_deleted),
    key idx_theme_stock_mapping_task (task_id, task_status, is_deleted),
    key idx_theme_stock_mapping_created (created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='题材股票映射表';

-- =========================================================
-- 04. 默认规则定义与规则版本初始化
-- 来源：sql/22_rule_version_seed.sql
-- =========================================================

-- 第八步：规则定义与默认启用版本初始化
-- 数据库：MySQL 8.0+
-- 执行前：use astock_business;

insert into rule_definition(rule_code, rule_name, rule_category, rule_desc, rule_status)
values
('EMOTION_STAGE_CORE', '情绪周期识别核心规则', 'ENGINE', '识别10阶段情绪周期，并输出评分明细与阶段快照', 'ENABLED'),
('SIMILARITY_MATCH_CORE', '历史相似行情匹配核心规则', 'ENGINE', '九维相似度匹配，不允许future字段参与T日匹配', 'ENABLED'),
('MAINLINE_RECOGNITION_CORE', '主线题材识别核心规则', 'ENGINE', '六维连续分识别主线，禁止涨幅第一或涨停最多硬判定', 'ENABLED'),
('LEADER_RECOGNITION_CORE', '龙头识别核心规则', 'ENGINE', '七维综合分识别龙头，禁止最高板等同市场总龙头', 'ENABLED'),
('PATTERN_CONDITION_CORE', '买点条件判定核心规则', 'ENGINE', '只输出条件状态，不输出交易建议', 'ENABLED'),
('RISK_CONTROL_CORE', '风控上级保护核心规则', 'ENGINE', '综合风险评分并覆盖模式风险否决', 'ENABLED'),
('BACKTEST_EXECUTION_CORE', '回测执行核心规则', 'ENGINE', 'future字段仅在历史回测窗口读取', 'ENABLED'),
('AGENT_AUDIT_CORE', 'Agent研发审计核心规则', 'ENGINE', '扫描Mock、交易建议词、future越界、字段血缘和发布闸门', 'ENABLED')
on duplicate key update
    rule_name = values(rule_name),
    rule_category = values(rule_category),
    rule_desc = values(rule_desc),
    rule_status = values(rule_status),
    updated_at = now();

insert into rule_version(rule_code, rule_name, version_no, version_name, version_status, active_flag, rule_content_json, param_schema_json)
values
('EMOTION_STAGE_CORE', '情绪周期识别核心规则', 'v1.0.0', '默认启用版本', 'ACTIVE', 1, json_object('formula','stage_score'), json_object()),
('SIMILARITY_MATCH_CORE', '历史相似行情匹配核心规则', 'v1.0.0', '默认启用版本', 'ACTIVE', 1, json_object('formula','nine_dimension_similarity'), json_object()),
('MAINLINE_RECOGNITION_CORE', '主线题材识别核心规则', 'v1.0.0', '默认启用版本', 'ACTIVE', 1, json_object('formula','mainline_strength_score'), json_object()),
('LEADER_RECOGNITION_CORE', '龙头识别核心规则', 'v1.0.0', '默认启用版本', 'ACTIVE', 1, json_object('formula','leader_score'), json_object()),
('PATTERN_CONDITION_CORE', '买点条件判定核心规则', 'v1.0.0', '默认启用版本', 'ACTIVE', 1, json_object('formula','pattern_condition_score'), json_object()),
('RISK_CONTROL_CORE', '风控上级保护核心规则', 'v1.0.0', '默认启用版本', 'ACTIVE', 1, json_object('formula','risk_score'), json_object()),
('BACKTEST_EXECUTION_CORE', '回测执行核心规则', 'v1.0.0', '默认启用版本', 'ACTIVE', 1, json_object('futureReadPhase','BACKTEST_WINDOW_ONLY'), json_object()),
('AGENT_AUDIT_CORE', 'Agent研发审计核心规则', 'v1.0.0', '默认启用版本', 'ACTIVE', 1, json_object('gates','release_gate'), json_object())
on duplicate key update
    version_status = values(version_status),
    active_flag = values(active_flag),
    rule_content_json = values(rule_content_json),
    param_schema_json = values(param_schema_json),
    updated_at = now();


-- =========================================================
-- 05. 页面字段血缘初始化数据
-- 来源：sql/07_page_field_lineage_seed.sql
-- =========================================================

-- 第七步第三段：PageVO公共字段血缘初始化数据
-- 说明：本脚本初始化当前工程骨架中已落地的公共字段映射。
-- 后续补齐完整PageVO业务字段时，需要继续向 page_contract_field_lineage 追加字段级映射。

INSERT INTO page_contract_field_lineage
(page_code, page_name, vo_class_name, field_name, field_comment, source_type, source_table, source_column, calculation_formula, required, audit_passed)
VALUES
('PAGE_01_MARKET_DASHBOARD','今日市场总览驾驶舱','MarketDashboardVO','tradeDate','tradeDate','CLICKHOUSE','market_factor_snapshot','trade_date','',1,1),
('PAGE_01_MARKET_DASHBOARD','今日市场总览驾驶舱','MarketDashboardVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_01_MARKET_DASHBOARD','今日市场总览驾驶舱','MarketDashboardVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_01_MARKET_DASHBOARD','今日市场总览驾驶舱','MarketDashboardVO','conclusion','conclusion','CLICKHOUSE','market_factor_snapshot','evidence_json','',1,1),
('PAGE_01_MARKET_DASHBOARD','今日市场总览驾驶舱','MarketDashboardVO','riskTips','riskTips','CLICKHOUSE','market_factor_snapshot','risk_json','',1,1),
('PAGE_02_HISTORICAL_SIMILARITY','历史相似行情匹配页','HistoricalSimilarityPageVO','tradeDate','tradeDate','CLICKHOUSE','historical_similarity_match','trade_date','',1,1),
('PAGE_02_HISTORICAL_SIMILARITY','历史相似行情匹配页','HistoricalSimilarityPageVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_02_HISTORICAL_SIMILARITY','历史相似行情匹配页','HistoricalSimilarityPageVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_02_HISTORICAL_SIMILARITY','历史相似行情匹配页','HistoricalSimilarityPageVO','conclusion','conclusion','CLICKHOUSE','historical_similarity_match','reference_text','',1,1),
('PAGE_02_HISTORICAL_SIMILARITY','历史相似行情匹配页','HistoricalSimilarityPageVO','riskTips','riskTips','CLICKHOUSE','historical_similarity_match','risk_text','',1,1),
('PAGE_03_EMOTION_STATE_MACHINE','情绪周期状态机页','EmotionCycleStateMachineVO','tradeDate','tradeDate','CLICKHOUSE','emotion_stage_snapshot','trade_date','',1,1),
('PAGE_03_EMOTION_STATE_MACHINE','情绪周期状态机页','EmotionCycleStateMachineVO','dataComplete','dataComplete','CALCULATION','emotion_stage_snapshot','data_complete','DataQualityQueryService.checkPage',1,1),
('PAGE_03_EMOTION_STATE_MACHINE','情绪周期状态机页','EmotionCycleStateMachineVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_03_EMOTION_STATE_MACHINE','情绪周期状态机页','EmotionCycleStateMachineVO','conclusion','conclusion','CLICKHOUSE','emotion_stage_snapshot','evidence_json','',1,1),
('PAGE_03_EMOTION_STATE_MACHINE','情绪周期状态机页','EmotionCycleStateMachineVO','riskTips','riskTips','CLICKHOUSE','emotion_stage_snapshot','risk_json','',1,1),
('PAGE_04_CYCLE_SAMPLE_LIBRARY','历史周期样本库页','HistoricalCycleSamplePageVO','tradeDate','tradeDate','CLICKHOUSE','historical_cycle_sample','trade_date','',1,1),
('PAGE_04_CYCLE_SAMPLE_LIBRARY','历史周期样本库页','HistoricalCycleSamplePageVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_04_CYCLE_SAMPLE_LIBRARY','历史周期样本库页','HistoricalCycleSamplePageVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_04_CYCLE_SAMPLE_LIBRARY','历史周期样本库页','HistoricalCycleSamplePageVO','conclusion','conclusion','CLICKHOUSE','historical_cycle_sample','evidence_json','',1,1),
('PAGE_04_CYCLE_SAMPLE_LIBRARY','历史周期样本库页','HistoricalCycleSamplePageVO','riskTips','riskTips','CLICKHOUSE','historical_cycle_sample','feature_json','',1,1),
('PAGE_05_MAINLINE_RADAR','主线题材雷达页','MainlineRadarPageVO','tradeDate','tradeDate','CLICKHOUSE','mainline_daily_snapshot','trade_date','',1,1),
('PAGE_05_MAINLINE_RADAR','主线题材雷达页','MainlineRadarPageVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_05_MAINLINE_RADAR','主线题材雷达页','MainlineRadarPageVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_05_MAINLINE_RADAR','主线题材雷达页','MainlineRadarPageVO','conclusion','conclusion','CLICKHOUSE','mainline_daily_snapshot','evidence_json','',1,1),
('PAGE_05_MAINLINE_RADAR','主线题材雷达页','MainlineRadarPageVO','riskTips','riskTips','CLICKHOUSE','mainline_daily_snapshot','risk_json','',1,1),
('PAGE_06_SECTOR_STRENGTH','板块强度排行页','SectorStrengthPageVO','tradeDate','tradeDate','CLICKHOUSE','sector_strength_snapshot','trade_date','',1,1),
('PAGE_06_SECTOR_STRENGTH','板块强度排行页','SectorStrengthPageVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_06_SECTOR_STRENGTH','板块强度排行页','SectorStrengthPageVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_06_SECTOR_STRENGTH','板块强度排行页','SectorStrengthPageVO','conclusion','conclusion','CLICKHOUSE','sector_strength_snapshot','evidence_json','',1,1),
('PAGE_06_SECTOR_STRENGTH','板块强度排行页','SectorStrengthPageVO','riskTips','riskTips','CLICKHOUSE','sector_strength_snapshot','risk_json','',1,1),
('PAGE_07_LEADER_LADDER','龙头梯队监控页','LeaderLadderPageVO','tradeDate','tradeDate','CLICKHOUSE','leader_daily_snapshot','trade_date','',1,1),
('PAGE_07_LEADER_LADDER','龙头梯队监控页','LeaderLadderPageVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_07_LEADER_LADDER','龙头梯队监控页','LeaderLadderPageVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_07_LEADER_LADDER','龙头梯队监控页','LeaderLadderPageVO','conclusion','conclusion','CLICKHOUSE','leader_daily_snapshot','evidence_json','',1,1),
('PAGE_07_LEADER_LADDER','龙头梯队监控页','LeaderLadderPageVO','riskTips','riskTips','CLICKHOUSE','leader_daily_snapshot','risk_json','',1,1),
('PAGE_09_PATTERN_CONDITION','买点条件判定页','PatternConditionPageVO','tradeDate','tradeDate','CLICKHOUSE','buy_pattern_signal_snapshot','trade_date','',1,1),
('PAGE_09_PATTERN_CONDITION','买点条件判定页','PatternConditionPageVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_09_PATTERN_CONDITION','买点条件判定页','PatternConditionPageVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_09_PATTERN_CONDITION','买点条件判定页','PatternConditionPageVO','conclusion','conclusion','CLICKHOUSE','buy_pattern_signal_snapshot','evidence_json','',1,1),
('PAGE_09_PATTERN_CONDITION','买点条件判定页','PatternConditionPageVO','riskTips','riskTips','CLICKHOUSE','buy_pattern_signal_snapshot','risk_veto_reason','',1,1),
('PAGE_10_RISK_CONTROL','风控与失效信号页','RiskControlPageVO','tradeDate','tradeDate','CLICKHOUSE','risk_signal_snapshot','trade_date','',1,1),
('PAGE_10_RISK_CONTROL','风控与失效信号页','RiskControlPageVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_10_RISK_CONTROL','风控与失效信号页','RiskControlPageVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_10_RISK_CONTROL','风控与失效信号页','RiskControlPageVO','conclusion','conclusion','CLICKHOUSE','risk_signal_snapshot','evidence_json','',1,1),
('PAGE_10_RISK_CONTROL','风控与失效信号页','RiskControlPageVO','riskTips','riskTips','CLICKHOUSE','risk_signal_snapshot','risk_action','',1,1),
('PAGE_11_BACKTEST_LAB','回测实验室','BacktestLabPageVO','tradeDate','tradeDate','CLICKHOUSE','backtest_layer_stat','trade_date','',1,1),
('PAGE_11_BACKTEST_LAB','回测实验室','BacktestLabPageVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_11_BACKTEST_LAB','回测实验室','BacktestLabPageVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_11_BACKTEST_LAB','回测实验室','BacktestLabPageVO','conclusion','conclusion','CLICKHOUSE','backtest_layer_stat','layer_text','',1,1),
('PAGE_11_BACKTEST_LAB','回测实验室','BacktestLabPageVO','riskTips','riskTips','CLICKHOUSE','backtest_layer_stat','layer_performance_level','',1,1),
('PAGE_13_DAILY_REVIEW','每日复盘工作台','DailyReviewWorkbenchVO','tradeDate','tradeDate','CLICKHOUSE','market_factor_snapshot','trade_date','',1,1),
('PAGE_13_DAILY_REVIEW','每日复盘工作台','DailyReviewWorkbenchVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_13_DAILY_REVIEW','每日复盘工作台','DailyReviewWorkbenchVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_13_DAILY_REVIEW','每日复盘工作台','DailyReviewWorkbenchVO','conclusion','conclusion','CLICKHOUSE','market_factor_snapshot','evidence_json','',1,1),
('PAGE_13_DAILY_REVIEW','每日复盘工作台','DailyReviewWorkbenchVO','riskTips','riskTips','CLICKHOUSE','market_factor_snapshot','features','',1,1),
('PAGE_14_RULE_VERSION','规则版本管理页','RuleVersionManagePageVO','tradeDate','tradeDate','MYSQL','','','',1,1),
('PAGE_14_RULE_VERSION','规则版本管理页','RuleVersionManagePageVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_14_RULE_VERSION','规则版本管理页','RuleVersionManagePageVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_14_RULE_VERSION','规则版本管理页','RuleVersionManagePageVO','conclusion','conclusion','MYSQL','rule_version','version_description','',1,1),
('PAGE_14_RULE_VERSION','规则版本管理页','RuleVersionManagePageVO','riskTips','riskTips','MYSQL','rule_version','config_json','',1,1),
('PAGE_15_AGENT_AUDIT','Agent研发审计页','AgentAuditDashboardVO','tradeDate','tradeDate','MYSQL','','','',1,1),
('PAGE_15_AGENT_AUDIT','Agent研发审计页','AgentAuditDashboardVO','dataComplete','dataComplete','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_15_AGENT_AUDIT','Agent研发审计页','AgentAuditDashboardVO','dataStatusText','dataStatusText','CALCULATION','','','DataQualityQueryService.checkPage',1,1),
('PAGE_15_AGENT_AUDIT','Agent研发审计页','AgentAuditDashboardVO','conclusion','conclusion','MYSQL','agent_audit_task','audit_summary','',1,1),
('PAGE_15_AGENT_AUDIT','Agent研发审计页','AgentAuditDashboardVO','riskTips','riskTips','MYSQL','agent_audit_task','status','',1,1)
;


-- =========================================================
-- MySQL 初始化完成
-- =========================================================
